version: '3'

services:
  db:
    build: ./db_service
    environment:
      MYSQL_DATABASE: shyftplan
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      DATABASE_HOST: db
      
  shyftplan:
    build: .
    environment:
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: shyftplan
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure 
