version: "3"
services:
  shyftplan-users:
    container_name: shyftplan-users
    restart: always
    build: .
    ports:
      - "8000:8000"

  mysql:
    image: mysql:8.0.2
    command: --default-authentication-plugin=mysql_native_password 
    environment:
      MYSQL_DATABASE: shyftplan
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'docker'
      MYSQL_ROOT_PASSWORD: root
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'